const healthcare = {
  title: "Healthcare Verification",

  description:
    "Verify healthcare institutions, pharmacies, hospitals, laboratories and medical organisations protected by IFSE.",

  verificationTypes: [
    {
      id: "community_pharmacy",
      name: "Verified Community Pharmacy",
      monthlyUSD: 60,
      badge: "Verified Community Pharmacy",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "hospital_pharmacy",
      name: "Verified Hospital Pharmacy",
      monthlyUSD: 80,
      badge: "Verified Hospital Pharmacy",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "clinic",
      name: "Verified Clinic",
      monthlyUSD: 75,
      badge: "Verified Clinic",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "specialist_clinic",
      name: "Verified Specialist Clinic",
      monthlyUSD: 100,
      badge: "Verified Specialist Clinic",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "medical_center",
      name: "Verified Medical Center",
      monthlyUSD: 120,
      badge: "Verified Medical Center",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "diagnostic_center",
      name: "Verified Diagnostic Center",
      monthlyUSD: 200,
      badge: "Verified Diagnostic Center",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "medical_laboratory",
      name: "Verified Medical Laboratory",
      monthlyUSD: 120,
      badge: "Verified Medical Laboratory",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "rehabilitation_center",
      name: "Verified Rehabilitation Center",
      monthlyUSD: 120,
      badge: "Verified Rehabilitation Center",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "maternity_center",
      name: "Verified Maternity Center",
      monthlyUSD: 150,
      badge: "Verified Maternity Center",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "dental_clinic",
      name: "Verified Dental Clinic",
      monthlyUSD: 100,
      badge: "Verified Dental Clinic",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "eye_clinic",
      name: "Verified Eye Clinic",
      monthlyUSD: 100,
      badge: "Verified Eye Clinic",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "mental_health_center",
      name: "Verified Mental Health Center",
      monthlyUSD: 120,
      badge: "Verified Mental Health Center",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "general_hospital",
      name: "Verified General Hospital",
      monthlyUSD: 75,
      badge: "Verified General Hospital",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },
    {
      id: "specialist_hospital",
      name: "Verified Specialist Hospital",
      monthlyUSD: 300,
      badge: "Verified Specialist Hospital",
      renewal: "Monthly",
      premium: true,
      ifseProtection: true,
    },

    {
      id: "pharmaceutical_company",
      name: "Verified Pharmaceutical Company",
      pricing: "Enterprise Negotiation",
      enterprise: true,
      contractRequired: true,
      renewal: "Contract",
      badge: "Verified Pharmaceutical Company",
      premium: true,
      ifseProtection: true,
      redirect: "/enterprise-partnership",
    },

    {
      id: "medical_equipment_manufacturer",
      name: "Verified Medical Equipment Manufacturer",
      pricing: "Enterprise Negotiation",
      enterprise: true,
      contractRequired: true,
      renewal: "Contract",
      badge: "Verified Medical Equipment Manufacturer",
      premium: true,
      ifseProtection: true,
      redirect: "/enterprise-partnership",
    },

    {
      id: "healthcare_group",
      name: "Healthcare Group",
      pricing: "Enterprise Negotiation",
      enterprise: true,
      contractRequired: true,
      renewal: "Contract",
      badge: "Verified Healthcare Group",
      premium: true,
      ifseProtection: true,
      redirect: "/enterprise-partnership",
    },
  ],
};

export default healthcare;
