const partnerships = {
  enterprise: {
    title: "Enterprise Partnership",
    pricing: "Private Enterprise Negotiation",
    renewal: "Annual Enterprise Contract",
    badge: "Enterprise Partner",
    enterprise: true,
    ifseProtection: true,
    redirect: "/enterprise-partnership",

    designedFor: [
      "Multinational Corporations",
      "Global Brands",
      "Manufacturers",
      "Telecommunications Providers",
      "Financial Institutions",
      "Airlines",
      "Pharmaceutical Companies",
      "Consumer Goods Companies",
      "Technology Companies",
      "Sports Brands",
      "Automobile Manufacturers",
      "Energy Companies",
      "Betting Companies",
      "Fashion Companies",
      "Luxury Brands",
      "Beverage Companies",
      "Media Conglomerates",
      "Logistics Companies",
      "Insurance Providers",
      "Industrial Companies",
      "Retail Chains",
      "Shopping Mall Operators",
      "Supermarket Chains",
      "Hospitality Groups",
      "Healthcare Networks",
      "Educational Networks",
      "Construction Companies",
      "Mining Companies",
      "Agricultural Companies",
      "Real Estate Developers",
      "Transportation Companies",
      "Aviation Companies",
      "Shipping Companies",
      "Entertainment Companies",
      "Tourism Companies",
      "Sports Organizations",
      "International NGOs",
      "Research Organizations",
      "Artificial Intelligence Companies",
      "Cloud Computing Providers",
      "Cybersecurity Companies",
      "Data Center Operators",
      "Payment Service Providers",
      "FinTech Companies",
      "Blockchain Companies",
      "and other eligible enterprises worldwide."
    ]
  },

  corporate: {
    title: "Corporate Partnership",
    pricing: "Private Enterprise Negotiation",
    renewal: "Annual Enterprise Contract",
    badge: "Corporate Partner",
    enterprise: true,
    ifseProtection: true,
    redirect: "/corporate-partnership",
  },

  government: {
    title: "Government Partnership",
    pricing: "Private Government Negotiation",
    renewal: "Government Partnership Contract",
    badge: "Government Partner",
    enterprise: true,
    ifseProtection: true,
    redirect: "/government-partnership",
  },
};

export default partnerships;
