export const IFSE = {
  version: "1.0",
  engine: "Inclura Fortress Security Engine",
  mandatory: true,
  defaultThreatLevel: "Low",

  riskLevels: [
    "Low",
    "Medium",
    "High",
    "Critical",
  ],

  reviewStages: [
    "Identity Verification",
    "Document Verification",
    "AI Fraud Detection",
    "Accessibility Compliance",
    "Compliance Review",
    "Security Review",
    "Manual Administrator Review",
    "Final Approval",
  ],

  protectedAccounts: [
    "Creator",
    "Business",
    "Organization",
    "NGO",
    "Institution",
    "Healthcare",
    "Media",
    "Corporate",
    "Government",
    "Enterprise",
    "Administrator",
  ],

  securityChecks: [
    "Identity Verification",
    "Government ID Validation",
    "Business Registration Validation",
    "AI Document Analysis",
    "Forgery Detection",
    "Duplicate Detection",
    "Device Fingerprinting",
    "IP Reputation",
    "VPN Detection",
    "TOR Detection",
    "Bot Detection",
    "Fraud Detection",
    "Accessibility Compliance",
    "Threat Assessment",
    "Risk Scoring",
    "Manual Review",
    "Audit Logging",
  ],
};
